### ISSUE TITLE
With GeoXML kmlrenderer and infowindow outside map directions form is not working

### ISSUE THREAD

**Issue by jmosmap** [jmosmap/plugin_googlemaps#17]
With GeoXML kmlrenderer and infowindow outside map directions form is not working

**Comment by jmosmap** [comment]
Solved the problem by updating the correct html instead of infowindow

**Comment by daniel-lucio** [comment]
Can you explain?

**Comment by jmosmap** [comment]
I changed the geoxml renderer to check if the infowindow is opened on the map or outside the map.
In release 3.4 it is solved. Email me on my website if you want to test this version.

**Comment by daniel-lucio** [comment]
Le 31 août 2015 16:06:14, vous avez écrit :

> Le 31 août 2015, 12:51:10 Mike Reumer a écrit :
> 
> > I changed the geoxml renderer to check if the infowindow is
> 
> opened on the
> 
> > map or outside the map. In release 3.4 it is solved. Email me
> 
> on my website
> 
> > if you want to test this version.
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/jmosmap/plugin_googlemaps/issues/17#issue
> > comment-13648121
> > 
> > 0
> 
> Replied

Yes, I would like 3.4 :)
